### ISSUE TITLE
PizzaCraft causes Advent of Ascension 3 and JEI to not work together

### ISSUE THREAD

**Issue by FlameyFaucet** [Tiviacz1337/PizzaCraft#51]
I have no idea why, but i had recently finished a modpack debug. This mod somehow managed to make AoA 3 and JEI to not work together; JEI will disappear if this combination of mods is present. Just Advent and JEI works fine, and my entire modpack works with JEI without PizzaCraft.

**Comment by Tslat** [comment]
Did some digging, turns out this is because PizzaCraft isn't registering its recipe types.

I threw a breakpoint on a mixin I have (the one that collides here), and it turns out it's failing because Minecraft doesn't know what kind of recipe PizzaCraft has, returning null, and giving an NPE

![image](https://user-images.githubusercontent.com/7098525/167356490-a8ddb7bf-e61f-496d-9ce6-7cbe88c54c96.png)
![image](https://user-images.githubusercontent.com/7098525/167356507-42b4c776-c891-4fa4-9008-0a1187e4b326.png)

@Tiviacz1337 register your recipe types properly please.

**Comment by Tiviacz1337** [comment]
Probably fixed in latest updates
